name: Validate Schema

on:
  push:
    paths:
      - "*.yaml"
      - "*.json"
  pull_request:
    paths:
      - "*.yaml"
      - "*.json"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: nwisbeta/validate-yaml-schema@v1.0.3
        with:
          yamlSchemasJson: |
            {
                "./schema.json": ["evcc.dist.yaml"]
            }
